### ISSUE TITLE
De taal

### ISSUE THREAD

**Issue by oliversipho** [Tristandemuijnck/profile-card-tristan#1]
https://github.com/Tristandemuijnck/profile-card-tristan/blob/985d1208245fb0c5807bdae5aca6feb254131420/index.html#L2

Top pagina, een tip de taal in html staat nog op Engels.

**Comment by Tristandemuijnck** [comment]
Fixed, 'en' veranderd naar 'nl'
https://github.com/Tristandemuijnck/profile-card-tristan/blob/fdced943f5134220067ab68989e49d7657117c23/index.html#L2
